name: Continuous Integration

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build
        run: docker-compose up --build -d

      - name: api_testing
        run: docker-compose run -e "RAILS_ENV=test" --rm api

      - name: client_testing 
        run: docker-compose run -e "NODE_ENV=testing" --rm client 
